//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computer()
        {
            this.Program_Computer = new HashSet<Program_Computer>();
            this.RaM_Computer = new HashSet<RaM_Computer>();
            this.User_Computer = new HashSet<User_Computer>();
        }
    
        public int IDComputer { get; set; }
        public string Network_name { get; set; }
        public string IpAddress { get; set; }
        public string Location { get; set; }
        public string System_unit { get; set; }
        public string System_board { get; set; }
        public string Processor { get; set; }
        public string RAM { get; set; }
        public string Video_card { get; set; }
        public string Video_memory { get; set; }
        public string HDD { get; set; }
        public string HDD_capacity { get; set; }
        public string CD_ROM { get; set; }
        public string Monitor { get; set; }
        public string Monitor_2 { get; set; }
        public string Keyboard { get; set; }
        public string Mouse { get; set; }
        public string Printer { get; set; }
        public string Scanner { get; set; }
        public decimal Price_all { get; set; }
        public System.DateTime Purchase_date { get; set; }
        public string OS { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program_Computer> Program_Computer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaM_Computer> RaM_Computer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Computer> User_Computer { get; set; }
    }
}
