//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountingEntities : DbContext
    {
        public AccountingEntities()
            : base("name=AccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computer> Computer { get; set; }
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<Program_Computer> Program_Computer { get; set; }
        public virtual DbSet<RaM> RaM { get; set; }
        public virtual DbSet<RaM_Computer> RaM_Computer { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_Computer> User_Computer { get; set; }
    }
}
