//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RaM()
        {
            this.RaM_Computer = new HashSet<RaM_Computer>();
        }
    
        public int IDRaM { get; set; }
        public System.DateTime Repair_date { get; set; }
        public string Description { get; set; }
        public string Type_of_repair { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaM_Computer> RaM_Computer { get; set; }
    }
}
